version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - checkout
      - run: 
          command: dotnet build
  lint:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - checkout
      - run: |
          export PATH="$PATH:/root/.dotnet/tools"
          dotnet tool install sharpidious --global
          sharpidious
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - checkout
      - run: 
          command: dotnet test
workflows:
  main:
    jobs:
      - build
      - lint
      - test